### ISSUE TITLE
Does this work with Mitsubishi SRK35ZMP-S?

### ISSUE THREAD

**Issue by jeroenterheerdt** [r45635/HVAC-IR-Control#21]
Would this library work with the Mitsubishi SRK35ZMP-S AC?

**Comment by Ericmas001** [comment]
According to this repo: https://github.com/ToniA/arduino-heatpumpir

The *ZMP models falls into the "Heavy" branch. (MitsubishiHeavyHeatpumpIR). Those are quite different from the supported models within the current library (MitsubishiHeatpumpIR).

So by reading the code, I assume no, this library wouldn't work

**Comment by jeroenterheerdt** [comment]
ok, thanks.
