### ISSUE TITLE
pin to connect

### ISSUE THREAD

**Issue by massilia31** [r45635/HVAC-IR-Control#3]
Hello,
I tried your project, but no reaction from the HVAC (Mitsubishi MFZ)

I wasn't able to found which pin is used for the transmition. Can You help me please?
Thank you.

**Comment by r45635** [comment]
Hello,
An IR LED must be connected to Arduino PWM pin 3.
Hope this help.
regards,

**Comment by massilia31** [comment]
Hello
Yes, it was helpful thanks.

The led is blinking but always no reaction on the HVAC (Mitsubishi MZF-KA50V)

Someone have an idea?

Regards

**Comment by r45635** [comment]
Hello @massilia31. Closed because of old issue, if still active then please reopen. regards, -r45635
